openapi: 3.0.1
info:
  title: STP Simulated Banking API (Beta)
  description: Core API For Simulated Banking
  version: 1.0.0
  contact: {}
tags:
  - name: walkability
    description: ''
servers:
  - url: https://hv6yubkb3xeg7ythedhym2jlsm0mohhz.lambda-url.us-east-1.on.aws/
paths:
  /api/v1/data/:
    get:
      tags:
        - walkability
      parameters:
        - name: area
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Good request
          content:
            application/json:
              schema: {}